blueprint:
  name: Window Open/Close Heating Control
  description: Turns off heating when a window is opened and restores the previous temperature when closed.
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: The binary sensor that detects if the window is open or closed.
      selector:
        entity:
          domain: binary_sensor
    heating_entity:
      name: Heating Entity
      description: The climate entity that controls the heating.
      selector:
        entity:
          domain: climate
    previous_temp_storage:
      name: Previous Temperature Storage
      description: Input_number entity to store the previous temperature.
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input window_sensor
    to: 'on'
  - platform: state
    entity_id: !input window_sensor
    to: 'off'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input window_sensor
            state: 'on'
        sequence:
          - service: script.set_previous_temperature
            data:
              heating_entity: !input heating_entity
              previous_temp_storage: !input previous_temp_storage
          - service: climate.set_hvac_mode
            target:
              entity_id: !input heating_entity
            data:
              hvac_mode: 'off'
      - conditions:
          - condition: state
            entity_id: !input window_sensor
            state: 'off'
        sequence:
          - service: script.restore_temperature
            data:
              heating_entity: !input heating_entity
              previous_temp_storage: !input previous_temp_storage

mode: single
