blueprint:
  name: 'Heating Schedule with Window Sensor and External Thermometer'
  description: 'Zapne vytápění v konkrétní dny a čas, pokud je okno zavřené a využívá externí teploměr pro měření teploty'
  domain: automation
  input:
    heating_entity:
      name: Heating Thermostat
      selector:
        entity:
          domain: climate
    window_sensor:
      name: Window Sensor
      selector:
        entity:
          domain: binary_sensor
    external_thermometer:
      name: External Thermometer
      selector:
        entity:
          domain: sensor
          device_class: temperature
    days_of_week:
      name: Days of the Week
      selector:
        entity:
          multiple: true
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
    time_to_start:
      name: Time to Start
      selector:
        time:
    target_temperature:
      name: Target Temperature
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
trigger:
  - platform: time
    at: !input time_to_start
condition:
  - condition: template
    value_template: >
      {{ now().strftime('%A').lower() in !input days_of_week | map('lower') and is_state(!input window_sensor, 'off') }}
action:
  - service: climate.set_temperature
    target:
      entity_id: !input heating_entity
    data:
      temperature: !input target_temperature
  - wait_for_trigger:
      - platform: state
        entity_id: !input window_sensor
        to: 'off'
    timeout: '1:00:00'
  - service: climate.turn_on
    target:
      entity_id: !input heating_entity
mode: single
