alias: Vypnout PC zásuvku při nízkém odběru
description: Vypne PC zásuvku pokud je spotřeba menší než 9 W po dobu 5 sekund
trigger:
  - platform: numeric_state
    entity_id: sensor.pc_power_switch_vykon
    below: 9
    for: "00:00:05"
action:
  - service: switch.turn_off
    target:
      entity_id: switch.pc_power_switch
mode: single
